// mobile/src/features/upgrade-to-premium/PremiumUpgradeModal.tsx
import { useState } from 'react';
import { Alert, Modal, Pressable, ScrollView, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { PLAN_PRICES, PREMIUM_FEATURES } from '@/entities/subscription';
import { Button } from '@/shared/ui/button';
import { Icon } from '@/shared/ui/icon';

import { usePremiumModalState } from './usePremiumFeature';

type Plan = 'premium_monthly' | 'premium_yearly';

export function PremiumUpgradeModal() {
  const { showUpgradeModal, upgradeFeatureName, closeModal } = usePremiumModalState();
  const [loadingPlan, setLoadingPlan] = useState<Plan | null>(null);

  async function handlePurchase(plan: Plan) {
    setLoadingPlan(plan);
    try {
      // IAP wiring lands in Task 57 (expo-iap). Until then keep the UX
      // discoverable so designers can review the gate flow end-to-end.
      Alert.alert(
        'Скоро',
        'Покупка через App Store / Google Play появится в ближайшем обновлении.',
      );
    } finally {
      setLoadingPlan(null);
    }
  }

  return (
    <Modal
      visible={showUpgradeModal}
      animationType="slide"
      presentationStyle="pageSheet"
      onRequestClose={closeModal}
    >
      <SafeAreaView
        edges={['top', 'bottom']}
        className="flex-1 bg-background-light dark:bg-background-dark"
      >
        <View className="flex-row items-center justify-between px-4 py-3">
          <Text className="text-xl font-bold text-text-light dark:text-text-dark">
            Ouro Premium
          </Text>
          <Pressable
            onPress={closeModal}
            accessibilityRole="button"
            accessibilityLabel="Закрыть"
            hitSlop={12}
          >
            <Icon name="close" size={24} />
          </Pressable>
        </View>

        <ScrollView className="flex-1 px-5" contentContainerClassName="pb-6 gap-5">
          {upgradeFeatureName ? (
            <Text className="text-sm text-text-muted-light dark:text-text-muted-dark">
              Функция «{upgradeFeatureName}» доступна с Premium-подпиской.
            </Text>
          ) : null}

          <View className="gap-3">
            {(PREMIUM_FEATURES as ReadonlyArray<{ icon: string; label: string; description: string }>).map((feature) => (
              <View key={feature.label} className="flex-row items-start gap-3">
                <Icon name={feature.icon} size={20} color="#FF9500" />
                <View className="flex-1">
                  <Text className="text-sm font-medium text-text-light dark:text-text-dark">
                    {feature.label}
                  </Text>
                  <Text className="text-xs text-text-muted-light dark:text-text-muted-dark">
                    {feature.description}
                  </Text>
                </View>
              </View>
            ))}
          </View>

          <Text className="text-xs text-center text-text-muted-light dark:text-text-muted-dark">
            7 дней бесплатно, затем от {PLAN_PRICES.premium_monthly}
          </Text>
        </ScrollView>

        <View className="px-5 pb-2 gap-2">
          <Button
            title={`${PLAN_PRICES.premium_yearly} — выгоднее`}
            variant="primary"
            loading={loadingPlan === 'premium_yearly'}
            disabled={loadingPlan !== null}
            onPress={() => handlePurchase('premium_yearly')}
          />
          <Button
            title={PLAN_PRICES.premium_monthly}
            variant="secondary"
            loading={loadingPlan === 'premium_monthly'}
            disabled={loadingPlan !== null}
            onPress={() => handlePurchase('premium_monthly')}
          />
        </View>
      </SafeAreaView>
    </Modal>
  );
}

// frontend/src/features/upgrade-to-premium/ui/PremiumUpgradeModal.vue
<script setup lang="ts">
import { UModal, UButton, UIcon } from '@/shared/ui';
import { PREMIUM_FEATURES, PLAN_PRICES } from '@/entities/subscription';
import { useUpgrade } from '../model/useUpgrade';

defineProps<{
  modelValue: boolean;
  featureName?: string;
}>();
const emit = defineEmits<{ 'update:modelValue': [value: boolean] }>();

const { isLoading, startCheckout } = useUpgrade();

function handlePurchase(plan: 'premium_monthly' | 'premium_yearly') {
  startCheckout(plan);
  emit('update:modelValue', false);
}
</script>

<template>
  <UModal
    :model-value="modelValue"
    title="Ouro Premium"
    @update:model-value="emit('update:modelValue', $event)"
  >
    <div class="space-y-5">
      <p v-if="featureName" class="text-sm text-text-secondary-light dark:text-text-secondary-dark">
        Функция «{{ featureName }}» доступна с Premium-подпиской.
      </p>

      <div class="space-y-3">
        <div v-for="feature in PREMIUM_FEATURES" :key="feature.label" class="flex items-start gap-3">
          <UIcon :name="feature.icon" size="sm" class="text-primary mt-0.5" />
          <div>
            <p class="text-sm font-medium text-text-primary-light dark:text-text-primary-dark">{{ feature.label }}</p>
            <p class="text-xs text-text-secondary-light dark:text-text-secondary-dark">{{ feature.description }}</p>
          </div>
        </div>
      </div>

      <p class="text-xs text-center text-text-tertiary-light dark:text-text-tertiary-dark">
        7 дней бесплатно, затем от {{ PLAN_PRICES.premium_monthly }}
      </p>
    </div>

    <template #actions>
      <UButton variant="primary" full-width :loading="isLoading" @click="handlePurchase('premium_yearly')">
        {{ PLAN_PRICES.premium_yearly }} — выгоднее
      </UButton>
      <UButton variant="secondary" full-width :loading="isLoading" @click="handlePurchase('premium_monthly')">
        {{ PLAN_PRICES.premium_monthly }}
      </UButton>
    </template>
  </UModal>
</template>
