// frontend/src/entities/transaction/ui/TransactionItem.vue
<script setup lang="ts">
import { computed, inject } from 'vue';
import { UIcon } from '@/shared/ui';
import { formatCurrency, COMPACT_FORMAT } from '@/shared/lib/format/currency';
import { formatRelativeDate } from '@/shared/lib/format/date';
import { getCategoryById as getCategoryByIdStatic } from '@/entities/category';
import type { Category } from '@/entities/category';
import { DEFAULT_CURRENCY } from '@/shared/config/currency';
import { TRANSFER_COLOR } from '@/shared/config/colors';
import type { Transaction } from '../model/types';

const props = defineProps<{
  transaction: Transaction;
  currency?: string;
  accountName?: string;
  toAccountName?: string;
  viewingAccountId?: string;
  balanceAfter?: number;
}>();
defineEmits<{
  click: [];
}>();
// Get getCategoryById from App.vue or fallback to static
const injectedGetCategoryById = inject<(id: string) => Category | undefined>('getCategoryById');
const getCategoryById = (id: string): Category | undefined => {
  return injectedGetCategoryById?.(id) ?? getCategoryByIdStatic(id);
};

const category = computed(() => getCategoryById(props.transaction.category_id));

const isTransfer = computed(() => props.transaction.type === 'transfer');
const isAdjustment = computed(() => props.transaction.type === 'adjustment');
const isInformational = computed(() => !!props.transaction.is_informational);

const isIncomingTransfer = computed(
  () =>
    isTransfer.value &&
    props.viewingAccountId &&
    props.transaction.to_account_id === props.viewingAccountId,
);

const transferLabel = computed(() => {
  if (!isTransfer.value) return '';
  const from = props.accountName || 'Счёт';
  const to = props.toAccountName || 'Счёт';

  if (props.viewingAccountId) {
    if (isIncomingTransfer.value) {
      return `← ${from}`;
    }
    return `→ ${to}`;
  }

  return `${from} → ${to}`;
});

// Use net_amount for expenses if available, otherwise use amount
const displayAmount = computed(() => {
  if (props.transaction.type === 'expense' && props.transaction.net_amount !== undefined) {
    return props.transaction.net_amount;
  }
  return props.transaction.amount;
});

const formattedAmount = computed(() => {
  const compact = COMPACT_FORMAT;
  if (isInformational.value) {
    const curr = props.transaction.currency || props.currency || DEFAULT_CURRENCY;
    return formatCurrency(props.transaction.amount, curr, compact);
  }
  if (isTransfer.value) {
    if (props.viewingAccountId) {
      if (isIncomingTransfer.value) {
        const amount = props.transaction.to_amount ?? props.transaction.amount;
        const curr =
          props.transaction.to_currency || props.transaction.currency || DEFAULT_CURRENCY;
        return `+${formatCurrency(amount, curr, compact)}`;
      }
      const curr = props.transaction.currency || props.currency || DEFAULT_CURRENCY;
      return `-${formatCurrency(props.transaction.amount, curr, compact)}`;
    }
    const curr = props.transaction.currency || props.currency || DEFAULT_CURRENCY;
    return formatCurrency(props.transaction.amount, curr, compact);
  }

  if (isAdjustment.value) {
    const prefix = props.transaction.is_debt_related ? '-' : '+';
    const curr = props.transaction.currency || props.currency || DEFAULT_CURRENCY;
    return `${prefix}${formatCurrency(props.transaction.amount, curr, compact)}`;
  }

  const prefix = props.transaction.type === 'income' ? '+' : '-';
  const curr = props.transaction.currency || props.currency || DEFAULT_CURRENCY;
  return `${prefix}${formatCurrency(displayAmount.value, curr, compact)}`;
});

const displayCurrency = computed(
  () => props.transaction.currency || props.currency || DEFAULT_CURRENCY,
);

const formattedDate = computed(() =>
  formatRelativeDate(new Date(props.transaction.date).getTime()),
);
</script>

<template>
  <button
    class="w-full flex items-center gap-3 p-3 rounded-lg transition-all duration-150 hover:bg-surface-light dark:hover:bg-surface-dark active:opacity-80 focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2 focus-visible:outline-none"
    :class="{ 'opacity-60': isInformational }"
    :aria-label="`${isTransfer ? 'Перевод' : category?.name || 'Транзакция'}, ${formattedAmount}`"
    @click="$emit('click')"
  >
    <!-- Category/Transfer Icon -->
    <div
      class="shrink-0 w-9 h-9 rounded-lg flex items-center justify-center"
      :style="{
        backgroundColor: isTransfer ? `${TRANSFER_COLOR}12` : `${category?.color || '#64748b'}12`,
      }"
    >
      <UIcon
        :name="isTransfer ? 'swap_horiz' : category?.icon || 'receipt_long'"
        size="sm"
        :style="{
          color: isTransfer ? TRANSFER_COLOR : category?.color || '#64748b',
        }"
      />
    </div>

    <!-- Content -->
    <div class="flex-1 text-left min-w-0">
      <p
        class="text-sm font-medium text-text-primary-light dark:text-text-primary-dark truncate flex items-center gap-1"
      >
        <span class="truncate">
          {{ isTransfer ? 'Перевод' : category?.name || 'Транзакция' }}
        </span>
        <span
          v-if="isInformational"
          class="shrink-0 inline-flex items-center gap-0.5 text-[10px] font-medium text-warning"
        >
          <UIcon name="volunteer_activism" size="xs" />
          Информационно
        </span>
      </p>
      <p class="text-xs text-text-tertiary-light dark:text-text-tertiary-dark truncate">
        <template v-if="isTransfer">{{ transferLabel }}</template>
        <template v-else>
          <span v-if="accountName">{{ accountName }}</span>
          <span v-if="accountName && (transaction.description || formattedDate)">·</span>
          <span>{{ transaction.description || formattedDate }}</span>
        </template>
      </p>
    </div>

    <!-- Amount -->
    <div class="text-right shrink-0">
      <p
        class="text-sm font-semibold"
        :class="[
          isInformational
            ? 'italic text-text-tertiary-light dark:text-text-tertiary-dark'
            : isAdjustment
              ? transaction.is_debt_related
                ? 'text-danger'
                : 'text-success'
              : isTransfer
                ? viewingAccountId
                  ? isIncomingTransfer
                    ? 'text-success'
                    : 'text-danger'
                  : 'text-primary'
                : transaction.type === 'income'
                  ? 'text-success'
                  : 'text-text-primary-light dark:text-text-primary-dark',
        ]"
      >
        {{ formattedAmount }}
      </p>
      <!-- Conversion for multi-currency transfers -->
      <p
        v-if="
          isTransfer &&
          !viewingAccountId &&
          transaction.to_currency &&
          transaction.to_currency !== transaction.currency
        "
        class="text-xs text-text-tertiary-light dark:text-text-tertiary-dark"
      >
        →
        {{ formatCurrency(transaction.to_amount || 0, transaction.to_currency, COMPACT_FORMAT) }}
      </p>
      <!-- Original amount indicator when there are debt returns -->
      <p
        v-if="!isInformational && transaction.has_debt_returns && transaction.type === 'expense'"
        class="text-xs text-text-tertiary-light dark:text-text-tertiary-dark line-through"
      >
        -{{ formatCurrency(transaction.amount, displayCurrency, COMPACT_FORMAT) }}
      </p>
      <!-- Balance after transaction -->
      <p
        v-if="balanceAfter !== undefined"
        class="text-caption-sm text-text-tertiary-light dark:text-text-tertiary-dark"
      >
        = {{ formatCurrency(balanceAfter, displayCurrency, COMPACT_FORMAT) }}
      </p>
    </div>
  </button>
</template>

// mobile/src/entities/transaction/ui/TransactionItem.tsx
import { useMemo } from 'react';
import { Pressable, Text, View } from 'react-native';

import { getCategoryById } from '@/entities/category';
import { TRANSFER_COLOR } from '@/shared/config/colors';
import { DEFAULT_CURRENCY } from '@/shared/config/currency';
import { COMPACT_FORMAT, formatCurrency } from '@/shared/lib/format/currency';
import { formatRelativeDate } from '@/shared/lib/format/date';
import { cn } from '@/shared/lib/utils';
import { Icon } from '@/shared/ui/icon';

import type { Transaction } from '../model/types';

export interface TransactionItemProps {
  transaction: Transaction;
  accountName?: string;
  toAccountName?: string;
  viewingAccountId?: string;
  onPress?: () => void;
}

export function TransactionItem({
  transaction,
  accountName,
  toAccountName,
  viewingAccountId,
  onPress,
}: TransactionItemProps) {
  const category = useMemo(() => getCategoryById(transaction.category_id), [transaction.category_id]);

  const isTransfer = transaction.type === 'transfer';
  const isAdjustment = transaction.type === 'adjustment';
  const isInformational = transaction.is_informational;
  const isIncomingTransfer =
    isTransfer && viewingAccountId !== undefined && transaction.to_account_id === viewingAccountId;

  const currency = transaction.currency || DEFAULT_CURRENCY;

  const displayAmount = useMemo(() => {
    if (transaction.type === 'expense' && transaction.net_amount !== undefined) {
      return transaction.net_amount;
    }
    return transaction.amount;
  }, [transaction]);

  const formattedAmount = useMemo(() => {
    const compact = COMPACT_FORMAT;
    if (isInformational) return formatCurrency(transaction.amount, currency, compact);
    if (isTransfer) {
      if (viewingAccountId) {
        if (isIncomingTransfer) {
          const incomingAmount = transaction.to_amount ?? transaction.amount;
          const incomingCurr = transaction.to_currency || currency;
          return `+${formatCurrency(incomingAmount, incomingCurr, compact)}`;
        }
        return `-${formatCurrency(transaction.amount, currency, compact)}`;
      }
      return formatCurrency(transaction.amount, currency, compact);
    }
    if (isAdjustment) {
      const prefix = transaction.is_debt_related ? '-' : '+';
      return `${prefix}${formatCurrency(transaction.amount, currency, compact)}`;
    }
    const prefix = transaction.type === 'income' ? '+' : '-';
    return `${prefix}${formatCurrency(displayAmount, currency, compact)}`;
  }, [
    transaction,
    currency,
    displayAmount,
    isAdjustment,
    isIncomingTransfer,
    isInformational,
    isTransfer,
    viewingAccountId,
  ]);

  const formattedDate = useMemo(
    () => formatRelativeDate(new Date(transaction.date).getTime()),
    [transaction.date],
  );

  const amountClassName = isInformational
    ? 'italic text-text-tertiary-light dark:text-text-tertiary-dark'
    : isAdjustment
      ? transaction.is_debt_related
        ? 'text-danger'
        : 'text-success'
      : isTransfer
        ? viewingAccountId
          ? isIncomingTransfer
            ? 'text-success'
            : 'text-danger'
          : 'text-primary'
        : transaction.type === 'income'
          ? 'text-success'
          : 'text-text-primary-light dark:text-text-primary-dark';

  const iconBgColor = isTransfer ? `${TRANSFER_COLOR}1F` : `${category?.color ?? '#64748b'}1F`;
  const iconColor = isTransfer ? TRANSFER_COLOR : category?.color ?? '#64748b';
  const iconName = isTransfer ? 'swap_horiz' : category?.icon ?? 'receipt_long';

  const transferLabel = isTransfer
    ? viewingAccountId
      ? isIncomingTransfer
        ? `← ${accountName ?? 'Счёт'}`
        : `→ ${toAccountName ?? 'Счёт'}`
      : `${accountName ?? 'Счёт'} → ${toAccountName ?? 'Счёт'}`
    : null;

  return (
    <Pressable
      onPress={onPress}
      accessibilityRole="button"
      className={cn(
        'flex-row items-center gap-3 rounded-lg p-3 active:opacity-80',
        isInformational && 'opacity-60',
      )}
    >
      <View
        className="h-9 w-9 shrink-0 items-center justify-center rounded-lg"
        style={{ backgroundColor: iconBgColor }}
      >
        <Icon name={iconName} size={18} color={iconColor} />
      </View>

      <View className="flex-1 min-w-0">
        <View className="flex-row items-center gap-1">
          <Text
            numberOfLines={1}
            className="text-sm font-medium text-text-primary-light dark:text-text-primary-dark"
          >
            {isTransfer ? 'Перевод' : category?.name ?? 'Транзакция'}
          </Text>
          {isInformational ? (
            <Text className="text-[10px] font-medium text-warning">Информационно</Text>
          ) : null}
        </View>
        <Text
          numberOfLines={1}
          className="text-xs text-text-tertiary-light dark:text-text-tertiary-dark"
        >
          {isTransfer
            ? transferLabel
            : [accountName, transaction.description ?? formattedDate].filter(Boolean).join(' · ')}
        </Text>
      </View>

      <View className="items-end shrink-0">
        <Text
          className={cn('text-sm font-semibold', amountClassName)}
          style={{ fontVariant: ['tabular-nums'] }}
        >
          {formattedAmount}
        </Text>
      </View>
    </Pressable>
  );
}
