// frontend/src/features/create-subscription/ui/SubscriptionForm.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { UInput, UButton, UTabs, UToggle } from '@/shared/ui';
import { CategoryChips, EXPENSE_CATEGORIES } from '@/entities/category';
import { AccountSelector, useAccounts } from '@/entities/account';
import { CURRENCIES } from '@/entities/currency';
import { getCurrencySymbol } from '@/shared/lib/format/currency';
import {
  FREQUENCY_LABELS,
  type RecurringSubscriptionInsert,
} from '@/entities/recurring-subscription';
import { useCurrentUser } from '@/shared/lib/hooks/useCurrentUser';
import ServicePresetPicker from './ServicePresetPicker.vue';
import type { ServicePreset } from '@/entities/recurring-subscription';

const props = withDefaults(
  defineProps<{
    formData: RecurringSubscriptionInsert;
    isSubmitting?: boolean;
    submitLabel?: string;
    showPresetPicker?: boolean;
  }>(),
  {
    submitLabel: 'Создать',
    showPresetPicker: true,
  },
);

const emit = defineEmits<{
  'update:formData': [data: RecurringSubscriptionInsert];
  submit: [];
}>();

const { userId } = useCurrentUser();
const { accounts } = useAccounts(userId);

const selectedPresetKey = ref<string | null>(null);

const currencySymbol = computed(() => getCurrencySymbol(props.formData.currency));

const frequencyTabs = Object.entries(FREQUENCY_LABELS).map(([id, label]) => ({ id, label }));

function update<K extends keyof RecurringSubscriptionInsert>(
  field: K,
  value: RecurringSubscriptionInsert[K],
) {
  emit('update:formData', { ...props.formData, [field]: value });
}

function handlePresetSelect(preset: ServicePreset | null, key: string | null) {
  selectedPresetKey.value = key;
  if (preset) {
    emit('update:formData', {
      ...props.formData,
      name: preset.name,
      icon: preset.icon,
      color: preset.color,
    });
  } else {
    emit('update:formData', {
      ...props.formData,
      name: '',
      icon: 'subscriptions',
      color: '#6366f1',
    });
  }
}

function handleAccountSelect(accountId: string) {
  update('account_id', accountId);
}
</script>

<template>
  <form class="space-y-5" @submit.prevent="emit('submit')">
    <!-- Service preset picker -->
    <ServicePresetPicker
      v-if="showPresetPicker"
      :selected="selectedPresetKey"
      @select="handlePresetSelect"
    />

    <!-- Name -->
    <UInput
      :model-value="formData.name"
      label="Название"
      placeholder="Название подписки"
      @update:model-value="update('name', $event as string)"
    />

    <!-- Amount + Currency -->
    <div class="space-y-2">
      <label class="text-xs font-medium text-text-secondary-light dark:text-text-secondary-dark">
        Сумма
      </label>
      <div class="flex gap-2">
        <div class="relative shrink-0">
          <select
            :value="formData.currency"
            class="appearance-none h-full bg-surface-light dark:bg-surface-dark rounded-xl px-3 pr-8 text-sm font-medium border border-border-light dark:border-border-dark focus:outline-none focus:ring-2 focus:ring-primary text-text-primary-light dark:text-text-primary-dark"
            @change="update('currency', ($event.target as HTMLSelectElement).value)"
          >
            <option v-for="c in CURRENCIES" :key="c.code" :value="c.code">
              {{ c.flag }} {{ c.code }}
            </option>
          </select>
        </div>
        <div class="flex-1">
          <UInput
            :model-value="String(formData.amount || '')"
            placeholder="0"
            variant="currency"
            type="number"
            :suffix="currencySymbol"
            @update:model-value="update('amount', Number($event) || 0)"
          />
        </div>
      </div>
    </div>

    <!-- Account -->
    <div v-if="accounts.length > 0" class="space-y-2">
      <label class="text-xs font-medium text-text-secondary-light dark:text-text-secondary-dark">
        Счёт для списания
      </label>
      <AccountSelector
        :accounts="accounts"
        :selected-id="formData.account_id ?? null"
        label="Счёт"
        @select="handleAccountSelect"
      />
    </div>

    <!-- Frequency -->
    <div class="space-y-2">
      <label class="text-xs font-medium text-text-secondary-light dark:text-text-secondary-dark">
        Частота
      </label>
      <UTabs
        :model-value="formData.frequency"
        :items="frequencyTabs"
        size="sm"
        @update:model-value="
          update('frequency', $event as RecurringSubscriptionInsert['frequency'])
        "
      />
      <!-- Custom frequency days -->
      <UInput
        v-if="formData.frequency === 'custom'"
        :model-value="String(formData.frequency_days || '')"
        label="Количество дней"
        placeholder="30"
        type="number"
        @update:model-value="update('frequency_days', Number($event) || undefined)"
      />
    </div>

    <!-- Billing date -->
    <UInput
      :model-value="formData.billing_date"
      label="Дата списания"
      type="date"
      @update:model-value="update('billing_date', $event as string)"
    />

    <!-- Category -->
    <div class="space-y-2">
      <label class="text-xs font-medium text-text-secondary-light dark:text-text-secondary-dark">
        Категория
      </label>
      <CategoryChips
        :categories="EXPENSE_CATEGORIES"
        :selected-id="formData.category_id || 'entertainment'"
        :rows="1"
        @select="update('category_id', $event)"
      />
    </div>

    <!-- Notify days before -->
    <UInput
      :model-value="String(formData.notify_days_before ?? 2)"
      label="Напомнить за (дней)"
      type="number"
      placeholder="2"
      @update:model-value="
        update('notify_days_before', Math.min(30, Math.max(1, Number($event) || 1)))
      "
    />

    <!-- Auto-charge toggle -->
    <div
      class="flex items-center justify-between p-3 rounded-xl bg-surface-light dark:bg-surface-dark"
    >
      <div>
        <p class="text-sm font-medium text-text-primary-light dark:text-text-primary-dark">
          Автоматическое списание
        </p>
        <p class="text-xs text-text-tertiary-light dark:text-text-tertiary-dark mt-0.5">
          Списывать автоматически в день оплаты
        </p>
      </div>
      <UToggle
        :model-value="formData.auto_charge ?? false"
        @update:model-value="update('auto_charge', $event)"
      />
    </div>

    <!-- Description -->
    <UInput
      :model-value="formData.description || ''"
      label="Описание (необязательно)"
      placeholder="Добавьте описание..."
      @update:model-value="update('description', $event as string)"
    />

    <!-- Submit button -->
    <UButton type="submit" variant="primary" size="xl" full-width :loading="isSubmitting">
      {{ submitLabel }}
    </UButton>
  </form>
</template>

// mobile/src/features/create-subscription/components/SubscriptionForm.tsx
import { useEffect, useState } from 'react';
import { Modal, Pressable, ScrollView, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';

import { useAccounts } from '@/entities/account/api/useAccounts';
import { useCategories } from '@/entities/category/api/useCategories';
import { CURRENCIES } from '@/entities/currency/model/constants';
import type {
  RecurringSubscription,
  RecurringSubscriptionInsert,
  SubscriptionFrequency,
} from '@/entities/recurring-subscription/model/types';
import { useAuthStore } from '@/shared/api/composables/useAuth';
import { ENTITY_COLORS } from '@/shared/config/colors';
import { cn } from '@/shared/lib/utils';
import { Button } from '@/shared/ui/button';

const FREQUENCIES: { id: SubscriptionFrequency; label: string }[] = [
  { id: 'weekly', label: 'Еженедельно' },
  { id: 'monthly', label: 'Ежемесячно' },
  { id: 'quarterly', label: 'Раз в квартал' },
  { id: 'yearly', label: 'Ежегодно' },
];

export type SubscriptionFormData = Omit<RecurringSubscriptionInsert, 'icon' | 'color'>;

type Props = {
  initial?: RecurringSubscription;
  onSubmit: (data: RecurringSubscriptionInsert) => Promise<void>;
  onClose: () => void;
  isSubmitting?: boolean;
};

export function SubscriptionForm({ initial, onSubmit, onClose, isSubmitting = false }: Props) {
  const user = useAuthStore((s) => s.user);
  const { data: accounts = [] } = useAccounts(user?.id ?? null);
  const { data: categories = [] } = useCategories(user?.id ?? null);

  const expenseCategories = categories.filter((c) => c.type === 'expense');

  const [name, setName] = useState(initial?.name ?? '');
  const [amount, setAmount] = useState(initial ? String(initial.amount) : '');
  const [currency, setCurrency] = useState(initial?.currency ?? 'USD');
  const [accountId, setAccountId] = useState<string | undefined>(initial?.account_id ?? undefined);
  const [categoryId, setCategoryId] = useState<string | undefined>(
    initial?.category_id ?? undefined,
  );
  const [frequency, setFrequency] = useState<SubscriptionFrequency>(
    initial?.frequency ?? 'monthly',
  );
  const [billingDate, setBillingDate] = useState(initial?.billing_date ?? '');
  const [color, setColor] = useState(initial?.color ?? (ENTITY_COLORS[0] as string));

  useEffect(() => {
    if (initial) {
      setName(initial.name);
      setAmount(String(initial.amount));
      setCurrency(initial.currency);
      setAccountId(initial.account_id ?? undefined);
      setCategoryId(initial.category_id ?? undefined);
      setFrequency(initial.frequency);
      setBillingDate(initial.billing_date);
      setColor(initial.color);
    }
  }, [initial]);

  const canSubmit =
    name.trim().length > 0 &&
    parseFloat(amount) > 0 &&
    billingDate.trim().length > 0 &&
    !isSubmitting;

  const handleSubmit = async () => {
    if (!canSubmit) return;
    const parsed = parseFloat(amount);
    if (isNaN(parsed) || parsed <= 0) return;

    await onSubmit({
      name: name.trim(),
      amount: parsed,
      currency,
      account_id: accountId,
      category_id: categoryId,
      frequency,
      billing_date: billingDate.trim(),
      icon: 'subscriptions',
      color,
    });
  };

  return (
    <Modal visible animationType="slide" presentationStyle="formSheet" onRequestClose={onClose}>
      <SafeAreaView edges={['top']} className="flex-1 bg-background-light dark:bg-background-dark">
        {/* Header */}
        <View className="flex-row items-center justify-between px-4 py-3">
          <Text className="text-lg font-semibold text-text-primary-light dark:text-text-primary-dark">
            {initial ? 'Изменить подписку' : 'Новая подписка'}
          </Text>
          <Pressable onPress={onClose} accessibilityRole="button" accessibilityLabel="Закрыть">
            <Text className="text-base text-primary">Отмена</Text>
          </Pressable>
        </View>

        <ScrollView className="flex-1" contentContainerClassName="gap-4 px-4 pb-8">
          {/* Name */}
          <TextInput
            value={name}
            onChangeText={setName}
            placeholder="Название (Netflix, Spotify…)"
            accessibilityLabel="Название подписки"
            className="rounded-2xl bg-surface-light px-4 py-3 text-base text-text-primary-light dark:bg-surface-dark dark:text-text-primary-dark"
            autoFocus
            returnKeyType="next"
          />

          {/* Amount */}
          <TextInput
            value={amount}
            onChangeText={setAmount}
            placeholder="Сумма"
            accessibilityLabel="Сумма подписки"
            keyboardType="decimal-pad"
            className="rounded-2xl bg-surface-light px-4 py-3 text-base text-text-primary-light dark:bg-surface-dark dark:text-text-primary-dark"
          />

          {/* Currency */}
          <View>
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-secondary-light dark:text-text-secondary-dark">
              Валюта
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {CURRENCIES.map((c) => {
                const active = c.code === currency;
                return (
                  <Pressable
                    key={c.code}
                    onPress={() => setCurrency(c.code)}
                    accessibilityRole="button"
                    accessibilityState={{ selected: active }}
                    className={cn(
                      'rounded-full border px-3 py-1.5',
                      active
                        ? 'border-primary bg-primary'
                        : 'border-border-light dark:border-border-dark',
                    )}
                  >
                    <Text
                      className={cn(
                        'text-sm font-medium',
                        active
                          ? 'text-white'
                          : 'text-text-primary-light dark:text-text-primary-dark',
                      )}
                    >
                      {c.flag} {c.code}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
          </View>

          {/* Billing date */}
          <TextInput
            value={billingDate}
            onChangeText={setBillingDate}
            placeholder="Дата списания (YYYY-MM-DD)"
            accessibilityLabel="Дата следующего списания"
            className="rounded-2xl bg-surface-light px-4 py-3 text-base text-text-primary-light dark:bg-surface-dark dark:text-text-primary-dark"
          />

          {/* Frequency */}
          <View>
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-secondary-light dark:text-text-secondary-dark">
              Периодичность
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {FREQUENCIES.map((f) => {
                const active = f.id === frequency;
                return (
                  <Pressable
                    key={f.id}
                    onPress={() => setFrequency(f.id)}
                    accessibilityRole="button"
                    accessibilityState={{ selected: active }}
                    className={cn(
                      'rounded-full border px-3 py-1.5',
                      active
                        ? 'border-primary bg-primary'
                        : 'border-border-light dark:border-border-dark',
                    )}
                  >
                    <Text
                      className={cn(
                        'text-sm font-medium',
                        active
                          ? 'text-white'
                          : 'text-text-primary-light dark:text-text-primary-dark',
                      )}
                    >
                      {f.label}
                    </Text>
                  </Pressable>
                );
              })}
            </View>
          </View>

          {/* Account picker */}
          {accounts.length > 0 && (
            <View>
              <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-secondary-light dark:text-text-secondary-dark">
                Счёт (необязательно)
              </Text>
              <View className="flex-row flex-wrap gap-2">
                {accounts.map((acc) => {
                  const active = acc.id === accountId;
                  return (
                    <Pressable
                      key={acc.id}
                      onPress={() => setAccountId(active ? undefined : acc.id)}
                      accessibilityRole="button"
                      accessibilityState={{ selected: active }}
                      className={cn(
                        'rounded-full border px-3 py-1.5',
                        active
                          ? 'border-primary bg-primary'
                          : 'border-border-light dark:border-border-dark',
                      )}
                    >
                      <Text
                        className={cn(
                          'text-sm font-medium',
                          active
                            ? 'text-white'
                            : 'text-text-primary-light dark:text-text-primary-dark',
                        )}
                      >
                        {acc.name}
                      </Text>
                    </Pressable>
                  );
                })}
              </View>
            </View>
          )}

          {/* Category picker */}
          {expenseCategories.length > 0 && (
            <View>
              <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-secondary-light dark:text-text-secondary-dark">
                Категория (необязательно)
              </Text>
              <View className="flex-row flex-wrap gap-2">
                {expenseCategories.map((cat) => {
                  const active = cat.id === categoryId;
                  return (
                    <Pressable
                      key={cat.id}
                      onPress={() => setCategoryId(active ? undefined : cat.id)}
                      accessibilityRole="button"
                      accessibilityState={{ selected: active }}
                      className={cn(
                        'rounded-full border px-3 py-1.5',
                        active
                          ? 'border-primary bg-primary'
                          : 'border-border-light dark:border-border-dark',
                      )}
                    >
                      <Text
                        className={cn(
                          'text-sm font-medium',
                          active
                            ? 'text-white'
                            : 'text-text-primary-light dark:text-text-primary-dark',
                        )}
                      >
                        {cat.name}
                      </Text>
                    </Pressable>
                  );
                })}
              </View>
            </View>
          )}

          {/* Color */}
          <View>
            <Text className="mb-2 text-xs font-semibold uppercase tracking-wider text-text-secondary-light dark:text-text-secondary-dark">
              Цвет
            </Text>
            <View className="flex-row flex-wrap gap-2">
              {ENTITY_COLORS.map((c) => {
                const active = c === color;
                return (
                  <Pressable
                    key={c}
                    onPress={() => setColor(c)}
                    accessibilityRole="button"
                    accessibilityLabel={`Цвет ${c}`}
                    accessibilityState={{ selected: active }}
                    className={cn('h-10 w-10 rounded-full', active && 'border-2 border-primary')}
                    style={{ backgroundColor: c }}
                  />
                );
              })}
            </View>
          </View>
        </ScrollView>

        <View className="px-4 pb-4">
          <Button
            title={initial ? 'Сохранить' : 'Создать'}
            onPress={handleSubmit}
            disabled={!canSubmit}
            loading={isSubmitting}
          />
        </View>
      </SafeAreaView>
    </Modal>
  );
}
