// mobile/src/entities/account/ui/AccountSelector.tsx
import { Pressable, ScrollView, Text, View } from 'react-native';

import { cn } from '@/shared/lib/utils';
import { Icon } from '@/shared/ui/icon';

import type { Account } from '../model/types';

interface Props {
  accounts: Account[];
  value: string | null;
  onChange: (accountId: string) => void;
}

export function AccountSelector({ accounts, value, onChange }: Props) {
  return (
    <ScrollView
      horizontal
      showsHorizontalScrollIndicator={false}
      contentContainerStyle={{ gap: 8, paddingHorizontal: 4 }}
    >
      {accounts.map((account) => {
        const selected = value === account.id;
        return (
          <Pressable
            key={account.id}
            onPress={() => onChange(account.id)}
            accessibilityRole="button"
            accessibilityLabel={account.name}
            accessibilityState={{ selected }}
            className={cn(
              'flex-row items-center gap-2 rounded-full px-3 py-2 border',
              selected
                ? 'border-primary bg-primary/10'
                : 'border-border-light dark:border-border-dark bg-card-light dark:bg-card-dark',
            )}
          >
            <View
              className="h-6 w-6 items-center justify-center rounded-full"
              style={{ backgroundColor: `${account.color}1F` }}
            >
              <Icon name={account.icon} size={14} color={account.color} />
            </View>
            <Text
              numberOfLines={1}
              className={cn(
                'text-sm font-medium',
                selected
                  ? 'text-primary'
                  : 'text-text-primary-light dark:text-text-primary-dark',
              )}
            >
              {account.name}
            </Text>
          </Pressable>
        );
      })}
    </ScrollView>
  );
}

// frontend/src/features/add-transaction/ui/AccountSelector.vue
<script setup lang="ts">
import type { AccountWithBalances } from '@/entities/account';

defineProps<{
  accounts: AccountWithBalances[];
  selectedId: string | null;
  label: string;
}>();

const emit = defineEmits<{
  select: [accountId: string];
}>();
</script>

<template>
  <div class="space-y-2">
    <label
      class="text-xs font-medium text-text-secondary-light dark:text-text-secondary-dark"
    >
      {{ label }}
    </label>
    <div class="flex gap-1.5 overflow-x-auto pb-1 -mx-1 px-1">
      <button
        v-for="account in accounts"
        :key="account.id"
        type="button"
        :class="[
          'flex items-center gap-1.5 px-3 py-1.5 rounded-lg whitespace-nowrap transition-all text-sm',
          'border',
          selectedId === account.id
            ? 'border-primary bg-primary/10 text-primary'
            : 'border-border-light dark:border-border-dark text-text-secondary-light dark:text-text-secondary-dark',
        ]"
        @click="emit('select', account.id)"
      >
        <span
          class="w-2.5 h-2.5 rounded-full"
          :style="{ backgroundColor: account.color }"
        />
        {{ account.name }}
        <slot name="badge" :account="account">
          <span v-if="account.balances.length > 1" class="text-xs opacity-60">
            ({{ account.balances.length }})
          </span>
        </slot>
      </button>
    </div>
  </div>
</template>
