// mobile/src/shared/ui/initial-avatar.tsx
import { Text, View } from 'react-native';
import { cn } from '@/shared/lib/utils';

export type InitialAvatarProps = {
  name: string;
  color?: string;
  size?: 'sm' | 'md' | 'lg';
};

const SIZE_BOX = { sm: 'h-8 w-8', md: 'h-10 w-10', lg: 'h-14 w-14' };
const SIZE_TEXT = { sm: 'text-xs', md: 'text-sm', lg: 'text-base' };

export function InitialAvatar({ name, color = '#6B7280', size = 'md' }: InitialAvatarProps) {
  const initial = name.trim().charAt(0).toUpperCase() || '?';
  return (
    <View
      className={cn('items-center justify-center rounded-full', SIZE_BOX[size])}
      style={{ backgroundColor: color }}
      accessibilityRole="image"
      accessibilityLabel={`Avatar for ${name}`}
    >
      <Text className={cn('font-semibold text-white', SIZE_TEXT[size])}>{initial}</Text>
    </View>
  );
}

// frontend/src/shared/ui/initial-avatar/InitialAvatar.vue
<script setup lang="ts">
import { getInitial } from '@/shared/lib/format/text';

withDefaults(
  defineProps<{
    name: string;
    color: string;
    size?: 'xs' | 'sm' | 'md' | 'lg';
    /** Use translucent background with colored text instead of solid bg + white text */
    translucent?: boolean;
  }>(),
  {
    size: 'md',
    translucent: false,
  },
);

const sizeClasses: Record<string, string> = {
  xs: 'w-5 h-5 text-[10px]',
  sm: 'w-7 h-7 text-[10px]',
  md: 'w-8 h-8 text-xs',
  lg: 'w-10 h-10 text-sm',
};
</script>

<template>
  <div
    class="rounded-full flex items-center justify-center font-bold shrink-0"
    :class="[sizeClasses[size], translucent ? '' : 'text-white']"
    :style="{
      backgroundColor: translucent ? color + '18' : color,
      color: translucent ? color : undefined,
    }"
  >
    {{ getInitial(name) }}
  </div>
</template>
